version: '3.8'

services:
  web:
    build: .
    ports:
      - "39905:39905"  # 格式为 "主机端口:容器端口"
    environment:
      - PORT=39905
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/nginx/ssl  # 用于挂载 SSL 证书（生产环境使用） 